version: "2"
services:
  discount-service:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      - spring.data.mongodb.authentication-database=admin
      - spring.data.mongodb.host=mongo_db
      - spring.data.mongodb.port=27017
      - spring.data.mongodb.database=demo
    depends_on:
      - mongo_db
  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017